rest_manager_app/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :users, only: [:new, :create, :show, :destroy]
  resources :items
  resources :parties
  resources :orders

  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy'

end

rest_manager_app/app/models/item.rb
class Item < ActiveRecord::Base
  has_and_belongs_to_many :orders
end

rest_manager_app/app/models/order.rb
class Order < ActiveRecord::Base
  has_and_belongs_to_many :items
  has_one :party

end

rest_manager_app/app/models/party.rb
class Party < ActiveRecord::Base
  has_one :order, dependent: :destroy
end

rest_manager_app/app/models/user.rb
class User < ActiveRecord::Base

  validates :username, presence: true, uniqueness: true
  has_secure_password

end

rest_manager_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rest_manager_app/app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @item = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
    redirect_to items_path
  else
    redirect_to new_item_path
  end

  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to items_path
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :cuisine_type, :price)
  end


end

rest_manager_app/app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.order(:party_id)
    @items = Item.all
    @parties = Party.all
  end

  def show
    @orders = Order.find(params[:id])
  end

  def new
    @order = Order.new
    @orders = Order.all
    @items = Item.all
    @parties = Party.all
  end

  def create
    puts "Item ids #{params[:item][:item_id]}"
    food_items = params[:item][:item_id].drop(1).map{ |item| item.to_i}
    @items = Item.where("id in (?)", food_items)
    @order = Order.new(order_params)
      # items_array = params[:item]["item_id"].drop(1)
    if @order.save
        @items.each { |item|
          @order.items << item
        }
        redirect_to orders_path
    else
      redirect_to new_order_path
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path
  end


  private
  def order_params
    params.require(:order).permit(:party_id, :item_id)
  end

end

rest_manager_app/app/controllers/parties_controller.rb
class PartiesController < ApplicationController

  def index
    @party = Party.order(:id)
  end

  def new
    @party = Party.new
  end

  def create
    @party = Party.new(party_params)
    if @party.save
        redirect_to parties_path
    else
      redirect_to new_party_path
    end
  end

  def edit
    @party = Party.find(params[:id])
  end

  def update
    @party = Party.find(params[:id])
    @party.update(party_params)
    redirect_to parties_path
  end

  def destroy
    @party = Party.find(params[:id])
    @party.destroy
    redirect_to parties_path
  end

private

  def party_params
    params.require(:party).permit(:party_name, :guests, :order_id)
  end


end

rest_manager_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


def create
  user = User.find_by(username: params[:username])
  if user && user.authenticate(params[:password])
    session[:current_user_id] = user.id
    redirect_to user_path(user)
  else
    redirect_to root_path
  end
end

def destroy
  session[:current_user_id] = nil
  redirect_to root_path
end

end

rest_manager_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to root_path
    else
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    session[:current_user_id] = nil
    @user.destroy
    redirect_to root_path
  end

private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :role)
  end


end

rest_manager_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
end

rest_manager_app/app/helpers/application_helper.rb
module ApplicationHelper
end

rest_manager_app/app/views/items/edit.html.erb
<div class="form">

  <%= form_for @item do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %> <br>

  <%= f.label :cuisine_type %>
  <%= f.text_field :cuisine_type %> <br>

  <%= f.label :price %>
  <%= f.number_field :price %> <br>

  <%= f.submit "Commit Changes" %>

  <% end %>
</div>

rest_manager_app/app/views/items/index.html.erb
<div class="items-container">
  <% @item.each do |item| %>
    <div class="menu-items">
    <%= item.name %><br>
    <%= item.cuisine_type %><br>
    <%= item.price %>
    <%= link_to "Remove Item", item_path(item.id), :method => :delete %>
    <%= link_to "Edit Item", edit_item_path(item.id) %>
    </div>
  <% end %>
</div>

rest_manager_app/app/views/items/new.html.erb
<div class="form">

  <%= form_for @item do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %> <br>

  <%= f.label :cuisine_type %>
  <%= f.text_field :cuisine_type %> <br>

  <%= f.label :price %>
  <%= f.number_field :price %> <br>

  <%= f.submit "Add Item to Menu" %>

  <% end %>
</div>

rest_manager_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestManagerApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar">
    <div>RESTaurant Manager App</div>
    <div class="login">
      <% if session[:current_user_id] %>
        <h1>Welcome!</h1>
        <%= link_to "#{User.find(session[:current_user_id]).username}", user_path(session[:current_user_id]) %>
        <%= link_to "Logout", sessions_path, method: :delete %>
      <% else %>
        <p>Sign In</p>
        <%= form_tag(sessions_path) do %>
        <%= label_tag :username %>
        <%= text_field_tag :username %>
        <br>
        <%= label_tag :password %>
        <%= password_field_tag :password %>
        <br>
        <%= submit_tag "Login" %>
        <% end %>
        <p>Not a member yet?</p>
        <%= link_to "Sign up","/users/new" %>
      <% end %>
    <div>
  </nav>

<%= yield %>

</body>
</html>

rest_manager_app/app/views/orders/index.html.erb
<div>
  <% @orders.each do |order| %>
    <h1>Order: <%= order.party_id %></h1>
      <% order.items.each do |item| %>
        <div>
          Item: <%= item.name %><br />
          Price: $<%= item.price %><br />
        </div>
      <% end %>
      <button><%= link_to "Delete", order_path(order), :method => :delete %></button>
    <br />
    <% end %>
</div>

rest_manager_app/app/views/orders/new.html.erb
<h4>Order Form</h4>

<%= form_for @order do |f| %>

  <%= f.label :item %>
  <%= collection_select(:item, :item_id, @items, :id, :name, {}, {multiple: true}) %>
<br>
<br>
  <%= f.label :party %>
  <%= collection_select(:order, :party_id, @parties, :id, :party_name) %>
<br>
<br>
  <%= f.submit %>

<% end %>

rest_manager_app/app/views/parties/edit.html.erb
<div class="form">

  <%= form_for @party do |f| %>

  <%= f.label :party_name %>
  <%= f.text_field :party_name %> <br>

  <%= f.label :guests %>
  <%= f.number_field :guests %> <br>

  <%= f.submit "Edit Party" %>

  <% end %>
</div>

rest_manager_app/app/views/parties/index.html.erb
<div class="parties-container">
  <% @party.each do |party| %>
  <br>
      <div class="menu-items">
      Party ID: <%= party.id %> <br>
      Party Name: <%= party.party_name %><br>
      Number of Guests: <%= party.guests %><br>
      <%= link_to "Remove Party", party_path(party.id), :method => :delete %>
      <%= link_to "Edit Party", edit_party_path(party.id) %>
      <%= link_to "Add Order", new_order_path(party.id) %>
      <br>
      <br>
      </div>
  <% end %>
</div>

rest_manager_app/app/views/parties/new.html.erb
<div class="form">

  <%= form_for @party do |f| %>

  <%= f.label :party_name %>
  <%= f.text_field :party_name %> <br>

  <%= f.label :guests %>
  <%= f.number_field :guests %> <br>

  <%= f.submit "Add Party" %>

  <% end %>
</div>

rest_manager_app/app/views/users/new.html.erb
<div class="form">
  <%= form_for @user do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %> <br>

  <%= f.label :password %>
  <%= f.password_field :password %> <br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %> <br>

  <%= f.label :role %>
  <%= f.text_field :role %><br>

  <%= f.submit "Sign Up" %>

  <% end %>
</div>

rest_manager_app/app/views/users/show.html.erb
<div id="show-user">
  <div>Welcome Back! <%= @user.username %> </div>
  
</div>